---
title: "Quantifying environmental trends: Disentangling changes in  impact from changes in monitoring"
author: "emLab, UCSB and GFW"
date: last-modified
date-format: "[Last Updated on] MMMM DD, YYYY"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
editor_options: 
  chunk_output_type: console
execute: 
  cache: true
editor: 
  markdown: 
    wrap: 72
---

```{r, echo = FALSE, results = FALSE, message = FALSE, warning = FALSE, cache = FALSE}
#| label: document-setup

# Set default chunk options
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, dev = "png")

# Load librariers
library(ggplot2)

# Set consistent theme for all plots
theme_plot <- function(){
  theme_minimal() %+replace%
    theme(axis.title.x = element_text(face = "bold"),
          axis.title.y = element_text(angle = 90,
                                      face = "bold",
                                      vjust = 3),
          strip.text.x = element_text(angle = 0,
                                      face = "bold"),
          strip.text.y = element_text(angle = 0,
                                      face = "bold"))}

# Set consistent theme for maps
# Based loosely off fishwatchr::theme_gfw_map()
# https://github.com/GlobalFishingWatch/fishwatchr/blob/master/R/theme_gfw_map.R
theme_map <- function(){
  theme_minimal() %+replace%
    theme(panel.background = element_rect(fill = "black"),
          legend.position = "bottom",
          legend.direction = "horizontal",
          plot.title = element_text(hjust = 0.5),
          panel.grid.minor = element_line(color = "black"),
          panel.grid.major = element_line(color = "black"),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          strip.background = element_rect(fill=NA,color=NA),
          plot.margin = unit(c(0.25,0,0,0), "cm"))
}

land <- rnaturalearth::ne_countries(returnclass = "sf") |>
  dplyr::select(geometry)


data_directory_base <-  ifelse(Sys.info()["nodename"] == "quebracho" | Sys.info()["nodename"] == "sequoia",
                               "/home/emlab",
                               # Otherwise, set the directory for local machines based on the OS
                               # If using Mac OS, the directory will be automatically set as follows
                               ifelse(Sys.info()["sysname"]=="Darwin",
                                      "/Users/Shared/nextcloud/emLab",
                                      # If using Windows, the directory will be automatically set as follows
                                      ifelse(Sys.info()["sysname"]=="Windows",
                                             "G:/Shared\ drives/nextcloud/emLab",
                                             # If using Linux, will need to manually modify the following directory path based on their user name
                                             # Replace your_username with your local machine user name
                                             "/home/your_username/Nextcloud")))

project_directory <- glue::glue("{data_directory_base}/projects/current-projects/paper-ocean-ghg")                           
```

```{r cache = FALSE}
#| label: load-data

# Annual CO2 emissions data for AIS-broadcasting fleet and dark fleet
annual_co2_emissions <- glue::glue("{project_directory}/data/processed/annual_co2_emissions.csv") |>
  readr::read_csv() |>
  dplyr::mutate(total_co2_emissions = emissions_co2_mt + emissions_co2_dark_mt) |>
  tidyr::pivot_longer(cols = -year,
                      names_to = "fleet",
                      values_to = "co2_emissions") |>
  dplyr::mutate(fleet = dplyr::case_when(stringr::str_detect(fleet,"dark") ~ "Non-broadcasting",
                                         stringr::str_detect(fleet,"total") ~ "Both fleets",
                                         TRUE ~ "AIS-broadcasting"))

# Annual AIS-based CO2 emissions, hours, average speed, and main engine power by vessel
annual_ais_co2_emissions_by_vessel <- glue::glue("{project_directory}/data/processed/annual_ais_co2_emissions_by_vessel.csv") |>
  readr::read_csv()

# Annual spatial CO2 emissions, for AIS and dark fleets
annual_spatial_co2_emissions_ais_dark <-  glue::glue("{project_directory}/data/processed/annual_spatial_co2_emissions_ais_dark.csv") |>
  readr::read_csv()
```

# Paper figures

```{r}
#| label: fig-total-annual-emissions-by-fleet
#| fig-cap: Total global annual CO2 emissions by fleet. The percent change from 2016 to 2024 for each fleet is shown next to its line.
#| fig-width: 7.5
#| fig-height: 4

# Calculate the total percent change in emissions by fleet
total_percent_change_by_fleet <- annual_co2_emissions |>
  dplyr::filter(year %in% c(2016,2024)) |>
  dplyr::filter(fleet != "Both fleets") |>
  tidyr::pivot_wider(names_from = year,
                     values_from = co2_emissions) |>
  dplyr::mutate(percent_total_2024 = `2024`/sum(`2024`))  |>
  janitor::adorn_totals("row") |>
  dplyr::mutate(percent_total_2024 = scales::percent(percent_total_2024)) |>
  dplyr::mutate(percent_change = round(100*(`2024` - `2016`)/`2016`),
                percent_change = ifelse(percent_change>0,
                                        glue::glue("+{percent_change}%"),
                                        glue::glue("{percent_change}%")))

annual_co2_emissions |>
  ggplot(aes(x = year, y = co2_emissions, color = fleet)) +
  geom_line() +
  geom_text(data = total_percent_change_by_fleet,
            aes(label = percent_change,
                y = `2024`,
                x = 2024.5),
            show.legend = FALSE) +
  scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6),
                     limits = c(0,1.5e9)) + 
  scale_x_continuous(breaks = unique(annual_co2_emissions$year)) +
  scale_color_brewer(type = "qual",
                     palette = "Dark2",
                     breaks = c("Both fleets","AIS-broadcasting","Non-broadcasting")) +
  theme_plot() +
  labs(x = "",
       y = "Annual global CO2 emissions\n(millions metric tonnes)",
       color = "Fleet") +
  theme(panel.grid.minor.x = element_blank())
```

```{r}
#| label: tbl-total-annual-emissions-by-fleet
#| tbl-cap: Total global annual CO2 emissions (million metric tonnes) by fleet for 2016 and 2024. The percent of total 2024 emissions for each fleet is also shown, along with the percent change from 2016 to 2024 for each fleet.

total_percent_change_by_fleet |>
  dplyr::relocate(fleet,`2016`,`2024`,`percent_total_2024`) |>
  dplyr::mutate(across(c(`2016`,`2024`), ~signif(./1e6,3))) |>
  knitr::kable()
```



```{r}
#| label: fig-co2-emissions-change-ais-dark-map
#| fig-cap: Spatial change in CO2 emissions between 2016 and 2024 (metric tonnes) for the AIS-broadcasting fleet (top panel), non-broadcasting fleet (middle panel), and both fleets combined (bottom panel) at a 1x1 degree spatial resolution.
#| fig-width: 7.5
#| fig-height: 8

annual_spatial_co2_emissions_ais_dark  |>
  dplyr::filter(year %in% c(2016,2024)) |>
  dplyr::mutate(across(c(emissions_co2_mt,emissions_co2_dark_mt), ~tidyr::replace_na(.,0))) |>
  dplyr::mutate(`Both fleets` = emissions_co2_mt + emissions_co2_dark_mt) |>
  dplyr::rename(`AIS-broadcasting` = emissions_co2_mt,
                `Non-broadcasting` = emissions_co2_dark_mt) |>
  tidyr::pivot_longer(cols = -c(year,lon_bin,lat_bin)) |>
  tidyr::pivot_wider(names_from = year,
                     values_from = value) |>
  dplyr::mutate(change_emissions_co2 = `2024`-`2016`) |>
  dplyr::mutate(name = forcats::fct_relevel(name,
                                            c("AIS-broadcasting",
                                              "Non-broadcasting"))) |>
  ggplot() +
  geom_tile(aes(x = lon_bin,
                y = lat_bin,
                fill = change_emissions_co2)) +
 geom_sf(data = land,
          color = "#374a6d",
          fill = "#374a6d") +
  facet_wrap(name~., ncol=1) +
  scico::scale_fill_scico("Change in CO2 emissions\nfrom 2016 to 2024\n(MT)",
                          palette = "berlin",
                          midpoint = 0,
                          trans = ggallin::pseudolog10_trans,
                          na.value = "black",
                          breaks = c(-1e6,-1e3,0,1e3,1e6),
                          labels = scales::comma) +
  labs(x = '',
       y= '') +
  theme_map() +
  theme(legend.position = "right",
        legend.direction = "vertical") +
  guides(fill = guide_colorbar(title.position = "top",
                               title.hjust = 0.5,
                               frame.colour = "black",
                               ticks.colour = "black",
                               barwidth = unit(1, "cm"),
                               barheight = unit(5, "cm"))) +
  scale_x_continuous(expand = c(0, 1)) +
  scale_y_continuous(expand = c(0, 1)) 
```


```{r}
#| label: fig-total-annual-unique-vessels-hours-power
#| fig-cap: Annual unique number of AIS-broadcasting vessels (top panel); annual number of operating hours for AIS-broadcasting vessels (middle panel); and annual total engine power for those vessels (killowatt). The percent change from 2015 to 2024 is shown next to each line.
#| fig-width: 7.5
#| fig-height: 6

annual_vessel_summary_by_year <- annual_ais_co2_emissions_by_vessel |>
  dplyr::group_by(year) |>
  dplyr::summarize(n_distinct_vessels = dplyr::n_distinct(ssvid),
                   main_engine_power_kw = sum(main_engine_power_kw),
                   hours = sum(hours)) |>
  dplyr::ungroup()   |>
  tidyr::pivot_longer(-year) |>
  dplyr::mutate(name = dplyr::case_when(stringr::str_detect(name,"power") ~ "Total main engine power for AIS-broadcasting vessels (kW)",
                                        stringr::str_detect(name,"vessels") ~ "Number unique AIS-broadcasting vessels",
                                        TRUE ~ "Operating hours for AIS-broadcasting vessels"))

total_percent_change_vessel_summary  <-annual_vessel_summary_by_year |>
  dplyr::filter(year %in% max(year) | year %in% min(year)) |>
  dplyr::arrange(year) |> 
  dplyr::group_by(name) |> 
  dplyr::summarize(end_value = value[2],
                   percent_change = round(100*(value[2] - value[1])/value[1])) |>
  dplyr::ungroup() |>
  dplyr::mutate(percent_change = ifelse(percent_change>0,
                                        glue::glue("+{percent_change}%"),
                                        glue::glue("{percent_change}%")))

annual_vessel_summary_by_year|>
  ggplot(aes(x = year, y = value)) +
  geom_line() +
  geom_text(data = total_percent_change_vessel_summary,
            aes(label = percent_change,
                y = end_value,
                x = max(annual_vessel_summary_by_year$year)+.5),
            show.legend = FALSE)+
  facet_wrap(name~., ncol = 1, scales = "free_y") +
  scale_y_continuous(labels = scales::comma,
                     limits = c(0,NA)) + 
  scale_x_continuous(breaks = unique(annual_vessel_summary_by_year$year)) +
  theme_plot() +
  labs(x = "",
       y = "") +
  theme(panel.grid.minor.x = element_blank())
```

```{r}
#| label: fig-total-indicators-by-earliest-operation-year
#| fig-cap: Total global CO2 emissions; number unique vessels; operating hours; and total main engine power for the set of AIS-broadcasting vessels that have been operating since a given year, where each line is colored by the earliest operation year. The percent change from the earliest year to 2024 is shown next to its line.
#| fig-width: 7.5
#| fig-height: 9

# Standard error function
# https://www.r-bloggers.com/2022/03/calculate-standard-error-in-r/
std <- function(x) sd(x)/sqrt(length(x))

# For vessels that have been in operation since a given year, calculate their annual emissions
# Do this for every where from 2015 to 2022
annual_emissions_by_fleet_year <- purrr::map_df(seq(min(annual_ais_co2_emissions_by_vessel$year),
                                                    max(annual_ais_co2_emissions_by_vessel$year)-1),
                                                function(year_tmp){
                                                  # Find those vessels that have been operating since this
                                                  year_fleet <- annual_ais_co2_emissions_by_vessel |>
                                                    dplyr::filter(year == year_tmp) |>
                                                    dplyr::select(ssvid)
                                                  # For these vessels, calculate annual emissions
                                                  annual_ais_co2_emissions_by_vessel |>
                                                    dplyr::filter(year >= year_tmp) |>
                                                    dplyr::inner_join(year_fleet, by = "ssvid") |>
                                                    dplyr::group_by(year) |>
                                                    dplyr::summarize(dplyr::across(c(emissions_co2_mt,
                                                                            main_engine_power_kw,
                                                                            hours), c(mean = mean,sum = sum,std = std, median = median)),
                                                                     n_distinct_vessels = dplyr::n_distinct(ssvid)) |>
                                                    dplyr::ungroup() |>
                                                    dplyr::mutate(fleet_year = year_tmp)
                                                } )   |>
  tidyr::pivot_longer(-c(fleet_year,year)) 

# Calculate the total percent change in emissions by each operation year fleet
total_percent_change_by_fleet_year  <-annual_emissions_by_fleet_year |>
  dplyr::group_by(fleet_year) |>
  dplyr::filter(year %in% max(year) | year %in% min(year)) |>
  dplyr::arrange(year) |> 
  dplyr::ungroup() |>
  dplyr::group_by(name,fleet_year) |> 
  dplyr::summarize(end_value = value[2],
                   percent_change = round(100*(value[2] - value[1])/value[1])) |>
  dplyr::ungroup() |>
  dplyr::mutate(percent_change = ifelse(percent_change>0,
                                        glue::glue("+{percent_change}%"),
                                        glue::glue("{percent_change}%")))

annual_emissions_by_fleet_year   |>
  dplyr::filter(stringr::str_detect(name,"sum") | stringr::str_detect(name,"vessels")) |>
  ggplot(aes(x = year, y = value, color = as.factor(fleet_year), group = fleet_year)) +
  geom_line() +
  facet_wrap(name~., ncol = 1, scales = "free_y") +
  geom_text(data = total_percent_change_by_fleet_year|>
  dplyr::filter(stringr::str_detect(name,"sum") | stringr::str_detect(name,"vessels")),
            aes(label = percent_change,
                y = end_value,
                x = max(annual_emissions_by_fleet_year$year)+.5),
            show.legend = FALSE) +
  scale_y_continuous(labels = scales::comma,
                     limits = c(0,NA)) +
  paletteer::scale_color_paletteer_d(palette = "jcolors::pal10",
                                     guide = guide_legend(reverse = TRUE)) +
  scale_x_continuous(breaks = unique(annual_emissions_by_fleet_year$year)) +
  theme_plot() +
  labs(x = "",
       y = "",
       color = "Earliest\noperation\nyear") +
  theme(panel.grid.minor.x = element_blank())
```

```{r}
#| label: fig-individual-distribution-annual-emissions-hours-power
#| fig-cap: Annual distributions of individual per-vessel CO2 emissions (metric tonnes, top panel); operating hours (middle panel); and main engine power (panel). The point shows the mean value, and the error bars show +/- two standard errors.
#| fig-width: 7.5
#| fig-height: 5

annual_ais_co2_emissions_by_vessel |>
   tidyr::pivot_longer(-c(year,ssvid))|>
  dplyr::mutate(name = glue::glue("{name}_mean")) |>
  ggplot(aes(x = year, y = value, group = year))+ 
  stat_summary(fun = mean, geom = "point") + 
  stat_summary(fun.data = mean_se, geom = "errorbar", fun.args = list(mult = 2), width = 0.5)+
  facet_wrap(name~.,scales="free_y",ncol=1) +
  theme_plot()  +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = unique(annual_ais_co2_emissions_by_vessel$year)) +
  theme_plot() +
  labs(x = "",
       y = "") 
```


```{r}
#| label: fig-individual-distribution-annual-emissions-hours-power-by-earliest-operation-year
#| fig-cap: Annual mean of individual per-vessel CO2 emissions (metric tonnes, top panel); operating hours (middle panel); and main engine power (panel) for the set of AIS-broadcasting vessels that have been operating since a given year, where each line is colored by the earliest operation year. The percent change from the earliest year to 2024 is shown next to its line.
#| fig-width: 7.5
#| fig-height: 8

annual_emissions_by_fleet_year  |>
  dplyr::filter(stringr::str_detect(name,"mean")) |>
  ggplot(aes(x = year, y = value, group = fleet_year, color = as.factor(fleet_year)))+ 
  geom_line()  +
  geom_text(data = total_percent_change_by_fleet_year|>
  dplyr::filter(stringr::str_detect(name,"mean")),
            aes(label = percent_change,
                y = end_value,
                x = max(annual_emissions_by_fleet_year$year)+.5),
            show.legend = FALSE) +
  facet_wrap(name~.,scales="free_y",ncol=1) +
  theme_plot()  +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = unique(annual_emissions_by_fleet_year$year)) +
  theme_plot() +
  labs(x = "",
       y = "",
       color = "Earliest\noperation\nyear") +
  paletteer::scale_color_paletteer_d(palette = "jcolors::pal10") 
```

```{r}
#| label: fig-first-last-operation-year-histogram
#| fig-cap: Histograms showing the distribution of the first and last operation year of each vessel.
#| 
# Determine entry and exit year for each vessel
first_last_year_by_vessel <- annual_ais_co2_emissions_by_vessel |>
  dplyr::group_by(ssvid) |>
  dplyr::summarize(first_operation_year = min(year),
                   last_operation_year = max(year)) |>
  dplyr::ungroup()

first_last_year_by_vessel |>
  tidyr::pivot_longer(-ssvid) |>
  ggplot(aes(x = value)) +
  geom_histogram(bins = length(unique(annual_ais_co2_emissions_by_vessel$year)), color = "black") +
  facet_wrap(name~., ncol = 1) +
  facet_wrap(name~.,scales="free_y",ncol=1) +
  theme_plot()  +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = unique(annual_ais_co2_emissions_by_vessel$year)) +
  theme_plot() +
  labs(x = "",
       y = "Number vessels")+
  theme(panel.grid.minor = element_blank())
```


```{r}
#| label: fig-individual-distribution-annual-emissions-hours-power-by-first-year
#| fig-cap: Annual mean of individual per-vessel CO2 emissions (metric tonnes); mean per-vessel operating hours; mean per-vessel main engine power; and number of distinct vessels for the set of AIS-broadcasting vessels for each first year of operation, where each line is colored by the first operation year.
#| fig-width: 7.5
#| fig-height: 8

indicators_by_first_operation_year <- purrr::map_df(seq(min(first_last_year_by_vessel$first_operation_year),
                                                    max(first_last_year_by_vessel$first_operation_year)),
                                                function(year_tmp){
                                                  
                                                  year_fleet <- first_last_year_by_vessel |>
                                                    dplyr::filter(first_operation_year == year_tmp) 
                                                  # For these vessels, calculate annual emissions
                                                  annual_ais_co2_emissions_by_vessel |>
                                                    dplyr::inner_join(year_fleet, by = "ssvid") |>
                                                    dplyr::group_by(year) |>
                                                    dplyr::summarize(dplyr::across(c(emissions_co2_mt,
                                                                            main_engine_power_kw,
                                                                            hours), c(mean = mean,sum = sum,std = std, median = median)),
                                                                     n_distinct_vessels = dplyr::n_distinct(ssvid)) |>
                                                    dplyr::ungroup() |>
                                                    dplyr::mutate(fleet_year = year_tmp)
                                                }) |>
  tidyr::pivot_longer(-c(year,fleet_year))

indicators_by_first_operation_year  |>
  dplyr::filter(stringr::str_detect(name,"mean") |
                  stringr::str_detect(name,"vessel")) |>
  ggplot(aes(x = year, y = value, group = fleet_year, color = as.factor(fleet_year)))+ 
  geom_line()  +
  facet_wrap(name~.,scales="free_y",ncol=1) +
  theme_plot()  +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = unique(annual_emissions_by_fleet_year$year)) +
  theme_plot() +
  labs(x = "",
       y = "",
       color = "First\noperation\nyear") +
  paletteer::scale_color_paletteer_d(palette = "jcolors::pal10")  +
  theme(panel.grid.minor = element_blank())
```

```{r}
#| label: fig-individual-distribution-annual-emissions-hours-power-by-last-year
#| fig-cap: Annual mean of individual per-vessel CO2 emissions (metric tonnes); mean per-vessel operating hours; mean per-vessel main engine power; and number of distinct vessels for the set of AIS-broadcasting vessels for each last year of operation, where each line is colored by the last operation year.
#| fig-width: 7.5
#| fig-height: 8

indicators_by_last_operation_year <- purrr::map_df(seq(min(first_last_year_by_vessel$last_operation_year),
                                                    max(first_last_year_by_vessel$last_operation_year)),
                                                function(year_tmp){
                                                  
                                                  year_fleet <- first_last_year_by_vessel |>
                                                    dplyr::filter(last_operation_year == year_tmp) 
                                                  # For these vessels, calculate annual emissions
                                                  annual_ais_co2_emissions_by_vessel |>
                                                    dplyr::inner_join(year_fleet, by = "ssvid") |>
                                                    dplyr::group_by(year) |>
                                                    dplyr::summarize(dplyr::across(c(emissions_co2_mt,
                                                                            main_engine_power_kw,
                                                                            hours), c(mean = mean,sum = sum,std = std, median = median)),
                                                                     n_distinct_vessels = dplyr::n_distinct(ssvid)) |>
                                                    dplyr::ungroup() |>
                                                    dplyr::mutate(fleet_year = year_tmp)
                                                }) |>
  tidyr::pivot_longer(-c(year,fleet_year))

indicators_by_last_operation_year  |>
  dplyr::filter(stringr::str_detect(name,"mean") |
                  stringr::str_detect(name,"vessel")) |>
  ggplot(aes(x = year, y = value, group = fleet_year, color = as.factor(fleet_year)))+ 
  geom_line()  +
  facet_wrap(name~.,scales="free_y",ncol=1) +
  theme_plot()  +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = unique(annual_emissions_by_fleet_year$year)) +
  theme_plot() +
  labs(x = "",
       y = "",
       color = "Last\noperation\nyear") +
  paletteer::scale_color_paletteer_d(palette = "jcolors::pal10") +
  theme(panel.grid.minor = element_blank())
```