-- AIS-broadcasting CO2 emissions for the analysis end year, grouped into the
-- vessel class families used in Figure 3. The family CASE expression is
-- generated by vessel_class_family_sql() in r/functions.R, so these maps use
-- exactly the same roll-up as the bar chart.
WITH
  vessel_family AS(
  SELECT
    ssvid,
    {vessel_class_family_case} vessel_class_family
  FROM
    `world-fishing-827.proj_ocean_ghg.vessel_info_{run_version_ais}` ),
  -- The source table is gridded far finer than the analysis grid, which makes
  -- for a download too large to keep in the repo, so bin up to the analysis
  -- resolution here. lon_bin / lat_bin are the lower-left corner of each pixel,
  -- matching every other gridded dataset in this project (the notebook adds half
  -- a pixel to centre them).
  gridded_emissions AS(
  SELECT
    FLOOR(lon_bin / {pixel_size_analysis}) * {pixel_size_analysis} lon_bin,
    FLOOR(lat_bin / {pixel_size_analysis}) * {pixel_size_analysis} lat_bin,
    vessel_class_family,
    emissions_co2_mt
  FROM
    `world-fishing-827.proj_ocean_ghg.daily_gridded_emissions_by_vessel_{run_version_ais}`
  JOIN
    vessel_family
  USING
    (ssvid)
  WHERE
    EXTRACT(YEAR
    FROM
      date) = {analysis_end_year} )
SELECT
  lon_bin,
  lat_bin,
  vessel_class_family,
  SUM(emissions_co2_mt) emissions_co2_mt
FROM
  gridded_emissions
GROUP BY
  lon_bin,
  lat_bin,
  vessel_class_family
